// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Dojo.KataPotter.Test
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("EstimatePurchase")]
    public partial class EstimatePurchaseFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "EstimatePurchase.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EstimatePurchase", "\tAfin d\'acheter les livres de Harry Potter\r\n\tEn tant que client\r\n\tJe veux estimer" +
                    " la valeur de mon achat", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Acheter au meilleurs prix les livres Harry Potter")]
        [NUnit.Framework.TestCaseAttribute("1", "0", "0", "0", "0", "8", null)]
        [NUnit.Framework.TestCaseAttribute("2", "0", "0", "0", "0", "16.00", null)]
        [NUnit.Framework.TestCaseAttribute("1", "1", "0", "0", "0", "15.20", null)]
        [NUnit.Framework.TestCaseAttribute("1", "1", "1", "0", "0", "21.60", null)]
        [NUnit.Framework.TestCaseAttribute("1", "1", "1", "1", "0", "25.60", null)]
        [NUnit.Framework.TestCaseAttribute("1", "1", "1", "1", "1", "30.00", null)]
        [NUnit.Framework.TestCaseAttribute("2", "1", "0", "0", "0", "23.20", null)]
        [NUnit.Framework.TestCaseAttribute("2", "2", "2", "1", "1", "51.20", null)]
        public virtual void AcheterAuMeilleursPrixLesLivresHarryPotter(string nb_Copy_I, string nb_Copy_II, string nb_Copy_III, string nb_Copy_IV, string nb_Copy_V, string total, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Acheter au meilleurs prix les livres Harry Potter", null, exampleTags);
#line 6
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  testRunner.When(string.Format("J\'achète {0} copie(s) \"Harry Potter à l\'école des sorciers\"", nb_Copy_I), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
  testRunner.When(string.Format("J\'achète {0} copie(s) \"Harry Potter et la Chambre des secrets\"", nb_Copy_II), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 9
  testRunner.When(string.Format("J\'achète {0} copie(s) \"Harry Potter et le Prisonnier d\'Azkaban\"", nb_Copy_III), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
  testRunner.When(string.Format("J\'achète {0} copie(s) \"Harry Potter et la Coupe de feu\"", nb_Copy_IV), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
  testRunner.When(string.Format("J\'achète {0} copie(s) \"Harry Potter et l\'Ordre du Phénix\"", nb_Copy_V), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
  testRunner.Then(string.Format("Je dois payer {0}€", total), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
